name = "srible"
main = "dist/index.html"
compatibility_date = "2024-07-12"

[build]
  command = "npm run build"
  publish = "dist"

[build.upload]
  format = "service-worker"

[[routes]]
  pattern = "srible.com/*"
  zone_name = "srible.com"
  custom_domain = true
